bayesian_network:
  parameter_learning:
    method: bayesian
    params:
      prior_type: BDeu
  structure_learning:
    method: hill_climbing
    params:
      max_indegree: 5
      scoring_method: bic
anomaly_detection:
  method: AE
  rejection_rate: 0.05
  EVT_rejection_rate: 0.01
  score: mse
  explanations:
    type: 1
    unobserved: true
    misclassified: true